sonar.projectKey=akverma24400_mern-chat-app
sonar.organization=akverma24400

sonar.projectName=mern-chat-app
sonar.sources=frontend/src,backend
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**